### ISSUE TITLE
generate book module throws consistent error  'KeyError: 'test_writing_advice' with published example

### ISSUE THREAD

**Issue by MorenoLabs** [samholt/L2MAC#4]
Error: **KeyError: 'test_writing_advice'**

Traceback (most recent call last):
  File "/home/morenolabs/coding/experiments/codelama/book.py", line 3, in <module>
    book: dict = generate_book(
  File "/home/morenolabs/coding/experiments/codelama/.venv/lib/python3.10/site-packages/l2mac/core.py", line 210, in generate_book
    return run_l2mac(
  File "/home/morenolabs/coding/experiments/codelama/.venv/lib/python3.10/site-packages/l2mac/core.py", line 91, in run_l2mac
    output_file_store = l2mac_internal(
  File "/home/morenolabs/coding/experiments/codelama/.venv/lib/python3.10/site-packages/l2mac/core.py", line 170, in l2mac_internal
    output_file_store = l2mac.run(steps=steps)
  File "/home/morenolabs/coding/experiments/codelama/.venv/lib/python3.10/site-packages/l2mac/l2mac.py", line 218, in run
    return self._run(steps=steps)
  File "/home/morenolabs/coding/experiments/codelama/.venv/lib/python3.10/site-packages/l2mac/l2mac.py", line 384, in _run
    "content": self.l2mac_prompts.control_unit_cycle_message_to_check_if_instruction_complete.format(
KeyError: 'test_writing_advice'

**Comment by samholt** [comment]
Thank you for raising this, I'll look into this.

**Comment by samholt** [comment]
Hi @MorenoLabs,

Thank you so much for finding this. This has now been resolved, and the book example fully works in the latest release.

Best,
Sam
